import { Inter } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const Roboto = localFont({
	src: "../Roboto.woff2",
	display: "swap",
});

export const metadata = {
	title: "Portfolio",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={Roboto.className}>{children}</body>
		</html>
	);
}
